login_creds: {'user':'admin' , 'password':'admin123'}
GRAFANA_INFO: {'host': '3.16.78.171','port': 3000}
dashboard: ["Performance","SE Business Dashboard","SmartEdge-Network-Switch-Demo","Technical Dashboard","SE Business Dashboard","Node Exporter Full","BEAM"]

time_frame: 'from=now-5m&to=now'
pdf_filename: 'outfile123.pdf'
defaut_logger_path: /var/log/Main_App/
log_path: /var/log/Main_App/garfana.log
log_lavel: info
