login_creds: {'user':'admin' , 'password':'admin'}
GRAFANA_INFO: {'host': '13.16.7.17','port': 3000}
dashboard: ["Performance","Business Dashboard","Technical Dashboard","Node Exporter Full"]

time_frame: 'from=now-5m&to=now'
pdf_filename: 'report.pdf'
defaut_logger_path: /var/log/Main_App/
log_path: /var/log/Main_App/garfana.log
log_lavel: info
